### ISSUE TITLE
Course groups: no warning when deleting the course group

### ISSUE THREAD

**Issue by fak66** [cosnics/cosnics#10]
A coure administrator can delete a course group. All content (documents/fora) in a course group is deleted without warning.

**Comment by vanpouckesven** [comment]
![2017-05-04_1249](https://cloud.githubusercontent.com/assets/2194636/25700450/1d9fad04-30c8-11e7-8fdd-56c32a3abe4e.png)

This seems to be working for me. Can you provide us some more information?
