### ISSUE TITLE
View Scores of all users accross all exercises

### ISSUE THREAD

**Issue by fak66** [cosnics/cosnics#11]
Course>Administration>Reporting>Tools>Exercises row: no button "View Scores"
The ViewScores butten next to the "Details" button has disappeared.
Old LCMS4 link : .... index.php?application=weblcms&course=89&tool=reporting&go=course_viewer&browser=table&tool_action=viewer&reporting_viewer_action=viewer&template=application%5Cweblcms%5Cintegration%5Creporting%5CAssessmentScoresTemplate

**Comment by vanpouckesven** [comment]
Fixed in 2c9fd35d7f20f7542eae6f70e55a683c48a29e06
