### ISSUE TITLE
PHP7.1

### ISSUE THREAD

**Issue by vanpouckesven** [cosnics/cosnics#17]
Upgrading to PHP 7.1 is currently not possible due to breaking changes in PHP. PHP 7.1 has introduced  a new error that is thrown when a method / function is called with an invalid number of parameters (ArgumentCountError). 

It is in no way possible for the development team to search for all the possible places where this issue occurs. We have decided to upgrade our local development boxes to PHP 7.1 and to fix the most significant issues while developing. 

If you are developing / testing Chamilo you should upgrade to PHP 7.1 so you can help us determine bugs. DO NOT USE THIS VERSION IN PRODUCTION UNTIL WE SQUASHED MUST OF THE COMMON BUGS!

**Comment by pjbro** [comment]
Fixed
